module.exports = {
  handleError: require('./catch'),
  handleStats: require('./stats'),
  handlePing: require('./ping'),
  handleStart: require('./start'),
  handleHelp: require('./help'),
  handleDonate: require('./donate'),
  handleSticker: require('./sticker'),
  handleDeleteSticker: require('./sticker-delete'),
  handleRestoreSticker: require('./sticker-restore'),
  handlePacks: require('./packs'),
  handleSelectPack: require('./pack-select'),
  handleSelectGroupPack: require('./pack-select-group'),
  handleHidePack: require('./pack-hide'),
  handleRestorePack: require('./pack-restore'),
  handleCopyPack: require('./pack-copy'),
  handleCoedit: require('./coedit'),
  handleCatalog: require('./catalog'),
  handleSearchCatalog: require('./search-catalog'),
  handleGuide: require('./guide'),
  handleLanguage: require('./language'),
  handleEmoji: require('./emoji'),
  handleStickerUpade: require('./sticker-update'),
  handleInlineQuery: require('./inline-query'),
  handleBoostPack: require('./pack-boost'),
  handleGroupSettings: require('./group-settings')
}
